version: "3.9"

services:
  mysql:
    image: ubuntu:22.04
    ports:
      - 80:80
    networks:
      - sanlabz-network

  # mysql:
  #   image: mysql:8.0.28
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     TZ: America/Sao_Paulo
  #     MYSQL_ROOT_PASSWORD: admin#345
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: admin#345
  #     MYSQL_DATABASE: effa
  #     MYSQL_ROOT_HOST: '%'
  #     MYSQL_TCP_PORT: 3308
  #   ports:
  #     - "3308:3308"
  #   expose:
  #     - 3308
  #   networks:
  #     - sanlabz-network

networks:
  sanlabz-network:
    driver: bridge
